object Versions {
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.1"
    const val materialIconsExtended = "1.6.0-alpha07"
    const val navigationCompose = "2.5.3"
    const val lifecycleRuntimeCompose = "2.7.0-beta01"
    const val materialCompose = "1.4.0-beta01"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.45"
    const val hiltNavigationCompose = "1.1.0-beta01"
    const val serialization = "1.9.0"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val kotlinxSerializationConverter = "1.0.0"
    const val kotlinxSerializationJson = "1.6.0"
    const val retrofit2ConverterGson = "2.9.0"
    const val room = "2.5.0"
    // -----> Testing
    const val junit = "4.13.2"
    // -----> Core
    const val coreKtx = "1.9.0"
    const val appcompact = "1.6.1"
    const val activityCompose = "1.8.0"
    const val coreMaterial = "1.9.0"
    const val junitInstrument = "1.1.5"
    const val espressoCore = "3.5.1"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val serilization = "1.6.0"
    const val navigationUiKtx = "2.7.5"
    const val uiTextGoogleFonts = "1.5.2"
    const val javapoet = "1.13.0"
    const val datastorePreferences = "1.0.0"
    const val coreSplash = "1.1.0-alpha02"


}